Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    DynamoDBKey:
        Description: "The name of primary key for DynamoDB table."
        Type: "String"
    ElasticSearchUrl:
        Description: "The url for API access to ElasticSearch."
        Type: "String"
    ElasticSearchIndex:
        Description: "The name of ElasticSearch index to use."
        Type: "String"
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python3.6
            CodeUri: ./
            Environment:
                Variables:
                    ELASTICSEARCH_URL: !Ref ElasticSearchUrl
                    ELASTICSEARCH_INDEX: !Ref ElasticSearchIndex
                    KEY_NAME: !Ref DynamoDBKey
